In [1]:
import torchmetrics
import torch

In [2]:
def compute_f1(p, r):
    return 2 * (p * r)/(p+r) 

In [214]:
pred = torch.tensor([[1., 0, 1],
                     [0, 0, 1],
                     [0, 1, 1],
                     [1, 0, 0]])

In [215]:
target = torch.tensor([[1, 0, 0],
                        [0, 0, 1],
                        [0, 1, 0],
                        [0, 1, 0]])


In [216]:
micro_p = torchmetrics.Precision(num_classes=3, average='micro', mdmc_average='global')
micro_r = torchmetrics.Recall(num_classes=3, average='micro', mdmc_average='global')
micro_f1 = torchmetrics.F1(num_classes=3, average='micro', mdmc_average='global')


In [217]:
micro_p.update(pred, target)
micro_p.compute()

tensor(0.5000)

In [218]:
micro_r.update(pred, target)
micro_r.compute()

tensor(0.7500)

In [219]:
micro_f1.update(pred, target)
micro_f1.compute()

tensor(0.6000)

In [220]:
compute_f1(micro_p.compute(), micro_r.compute())

tensor(0.6000)

In [221]:
pred

tensor([[1., 0., 1.],
        [0., 0., 1.],
        [0., 1., 1.],
        [1., 0., 0.]])

In [222]:
target

tensor([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]])

In [223]:
macro_p_ex = torchmetrics.Precision(num_classes=3, average='samples', mdmc_average='global')
macro_r_ex = torchmetrics.Recall(num_classes=3, average='samples', mdmc_average='global')
macro_f1_ex = torchmetrics.F1(num_classes=3, average='samples', mdmc_average='global')


In [224]:
macro_p_ex.update(pred, target)
macro_p_ex.compute()

tensor(0.5000)

In [225]:
macro_r_ex.update(pred, target)
macro_r_ex.compute()

tensor(0.7500)

In [226]:
macro_f1_ex.update(pred, target)
macro_f1_ex.compute()

tensor(0.5833)

In [227]:
pred

tensor([[1., 0., 1.],
        [0., 0., 1.],
        [0., 1., 1.],
        [1., 0., 0.]])

In [228]:
target

tensor([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]])

In [229]:
macro_p_c = torchmetrics.Precision(num_classes=3, average='macro', mdmc_average='global')
macro_r_c = torchmetrics.Recall(num_classes=3, average='macro', mdmc_average='global')
macro_f1_c = torchmetrics.F1(num_classes=3, average='macro', mdmc_average='global')


In [230]:
macro_p_c.update(pred, target)
macro_p_c.compute()

tensor(0.6111)

In [231]:
macro_r_c.update(pred, target)
macro_r_c.compute()

tensor(0.8333)

In [232]:
macro_f1_c.update(pred, target)
macro_f1_c.compute()

tensor(0.6111)

In [233]:
pred

tensor([[1., 0., 1.],
        [0., 0., 1.],
        [0., 1., 1.],
        [1., 0., 0.]])

In [234]:
target

tensor([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]])

In [239]:
precisions = torch.tensor([.5, 1, .33])
recalls = torch.tensor([1, .5, 1])

In [240]:
f1s = (2 * precisions * recalls) / (precisions + recalls)

In [241]:
f1s

tensor([0.6667, 0.6667, 0.4962])

In [242]:
torch.mean(f1s)

tensor(0.6099)

# macro f1 is the average of macro f1s ... WRONG, has to be the f1 between precision and recall